Cars/Models/Car.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace Cars.Models
{
    public class Car
    {
        [Key]
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public int Doors { get; set; }
        public string Color { get; set; }
        public float Price { get; set; }
    }
}

Cars/Models/ErrorViewModel.cs
namespace Cars.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Cars/Controllers/CarController.cs
using Cars.Data;
using Cars.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Cars.Controllers
{
    public class CarController : Controller
    {
        private readonly CarContext _context;

        public CarController(CarContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Cars);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Car car)
        {
            if (ModelState.IsValid)
            {
                car.Id = _context.Cars.Max(x => x.Id) + 1;
                _context.Cars.Add(car);
                return RedirectToAction("Index");
            }

            return View(car);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var car = _context.Cars.FirstOrDefault(x => x.Id == id);

            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        [HttpPost]
        public IActionResult Edit(Car car)
        {
            if (ModelState.IsValid)
            {
                var index = _context.Cars.FindIndex(x => x.Id == car.Id);
                _context.Cars[index] = car;
                return RedirectToAction("Index");
            }

            return View(car);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var car = _context.Cars.FirstOrDefault(x => x.Id == id);

            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCar(int? id)
        {
            var car = _context.Cars.FirstOrDefault(x => x.Id == id);
            if (car == null)
            {
                return NotFound();
            }
            _context.Cars.Remove(car);
            return RedirectToAction("Index");
        }
    }
}

Cars/Controllers/HomeController.cs
using Cars.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Cars.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cars/Views/Car/Create.cshtml
@model Car


<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Add Car</h2>
    </div>

    <form method="post">
        <div asp-validation-summary="All"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Make">Make</label>
                <input type="text" class="form-control mb-3" asp-for="Make" placeholder="Enter Make">
                <span asp-validation-for="Make" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Model">Model</label>
                <input type="text" class="form-control mb-3" asp-for="Model" placeholder="Enter Model">
                <span asp-validation-for="Model" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Year">Year</label>
                <input type="number" class="form-control mb-3" asp-for="Year" placeholder="Enter Year">
                <span asp-validation-for="Year" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Doors">Doors</label>
                <input type="number" class="form-control" asp-for="Doors">
                <span asp-validation-for="Doors" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Color">Color</label>
                <input type="text" class="form-control" asp-for="Color">
                <span asp-validation-for="Color" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Price">Price</label>
                <input type="number" class="form-control" asp-for="Price">
                <span asp-validation-for="Price" class=" alert-danger"></span>
            </div>
        </div>


        <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Save</button>
        <a asp-controller="Car" asp-action="Index" class="btn btn-lg btn-warning p-2">Back To List</a>
    </form>

</div>


@*//for front end validations*@

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

Cars/Views/Car/Delete.cshtml
@model Car

<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Delete Car</h2>
    </div>

    <form method="post" asp-action="DeleteEmp">
        <input asp-for="Id" hidden />
        <div asp-validation-summary="All"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Make">Make</label>
                <input type="text" class="form-control mb-3" asp-for="Make" disabled>
                <span asp-validation-for="Make" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Model">Model</label>
                <input type="text" class="form-control mb-3" asp-for="Model" disabled>
                <span asp-validation-for="Model" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Year">Year</label>
                <input type="number" class="form-control mb-3" asp-for="Year" disabled>
                <span asp-validation-for="Year" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Doors">Doors</label>
                <input type="number" class="form-control" asp-for="Doors" disabled>
                <span asp-validation-for="Doors" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Color">Color</label>
                <input type="text" class="form-control" asp-for="Color" disabled>
                <span asp-validation-for="Color" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Price">Price</label>
                <input type="number" class="form-control" asp-for="Price" disabled>
                <span asp-validation-for="Price" class=" alert-danger"></span>
            </div>
        </div>


        <button type="submit" class="btn btn-lg btn-danger p-2"><i class="bi bi-trash-fill"></i>Delete</button>
        <a asp-controller="Car" asp-action="Index" class="btn btn-lg btn-warning p-2">Back To List</a>
    </form>

</div>


@*//for front end validations*@

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

Cars/Views/Car/Edit.cshtml
@model Car

<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Edit Car</h2>
    </div>

    <form method="post" asp-action="Edit">
        <div asp-validation-summary="All"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Make">Make</label>
                <input type="text" class="form-control mb-3" asp-for="Make" disabled>
                <span asp-validation-for="Make" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Model">Model</label>
                <input type="text" class="form-control mb-3" asp-for="Model" disabled>
                <span asp-validation-for="Model" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Year">Year</label>
                <input type="number" class="form-control mb-3" asp-for="Year" disabled>
                <span asp-validation-for="Year" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Doors">Doors</label>
                <input type="number" class="form-control" asp-for="Doors" disabled>
                <span asp-validation-for="Doors" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Color">Color</label>
                <input type="text" class="form-control" asp-for="Color" disabled>
                <span asp-validation-for="Color" class=" alert-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Price">Price</label>
                <input type="number" class="form-control" asp-for="Price" disabled>
                <span asp-validation-for="Price" class=" alert-danger"></span>
            </div>
        </div>


        <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Update</button>
        <a asp-controller="Car" asp-action="Index" class="btn btn-lg btn-warning p-2">Back To List</a>
    </form>

</div>


@*//for front end validations*@

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

Cars/Views/Car/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Car>

@{
}

<div role="group" class="w-60 btn-group">
    <a asp-controller="Car" asp-action="Create" class=" btn btn-sm btn-primary"><i class="bi bi-pencil-square"></i>Create</a>&nbsp;
</div>

<div class="container shadow p-5">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th scope="col">Make</th>
                <th scope="col">Model</th>
                <th scope="col">Year</th>
                <th scope="col">Doors</th>
                <th scope="col">Color</th>
                <th scope="col">Price</th>
                <th scope="col">Guess</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr id="@item.Id">
                    <td>
                        @item.Make
                    </td>
                    <td>
                        @item.Model
                    </td>
                    <td>
                        @item.Year
                    </td>
                    <td>
                        @item.Doors
                    </td>
                    <td>
                        @item.Color
                    </td>
                    <td>
                        <input type="button" class="showOrHide" value="Show Price">
                        <div style="display: none">@item.Price</div>
                    </td>
                    <td>
                        <input type="number">
                        <input type="button" class="guess" value="Guess!!!" data-price=@item.Price>
                    </td>
                    <td>
                        <div role="group" class="w-60 btn-group">
                            <a asp-controller="Car" asp-action="Edit" asp-route-id="@item.Id" class=" btn btn-sm btn-primary"><i class="bi bi-pencil-square"></i>Edit</a>&nbsp;
                            <a asp-controller="Car" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger"><i class="bi bi-trash-fill"></i>Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <p>
        Select concat (c.FirstName, ' ', c.LastName) as FullName, c.Age, o.OrderId, o.DateCreated, o.MethodOfPurchase as Purcharse Method, od.ProductNumber, od.ProductOrigin
        from Customer as c
        inner join Order as o
        on c.PersonID = o.PersonID
        inner join OrderDetails as od
        on o.OrderId = od.OrderId
        where od.ProductId = 1112222333
        </p>
</div>

@section Scripts
    {

    <script type="text/javascript">

        $(document).ready(function () {

            $(".showOrHide").click(function () {
                $(this).next().toggle();
            });

            $(".guess").click(function () {
                var guessPrice = $(this).prev().val();
                if (Math.abs(guessPrice - $(this).data("price")) <= 5000)
                    alert("Correct!");
                else
                    alert("Try again!")
            });

        });

    </script>
}



Cars/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Cars/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cars</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cars.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Car" asp-action="Index">Cars</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Cars - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>